name = "SydneyTrainGame"
uuid = "44cf1c21-ce87-43fc-9f4d-bf83d8bc8caf"
authors = ["gyndlf <james@zingel.co.nz> and contributors"]
version = "1.0.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
